apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-redis
  name: user-service-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: user-service-redis
