apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service-server
  name: user-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-server
  template:
    metadata:
      labels:
        app: user-service-server
    spec:
      containers:
        - image: nrpndr/user-service:1.0
          name: user-service-server
          ports:
            - containerPort: 9011
              protocol: TCP
      restartPolicy: Always