apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-mysqldb
  name: user-service-mysqldb
spec:
  ports:
    - name: "3306"
      port: 3306
  selector:
    app: user-service-mysqldb
